IF(NOT LIBSCRYPT_LIBRARY)

FIND_PATH (LIBSCRYPT_INCLUDE_DIR
  NAMES libscrypt.h
  PATH_SUFFIXES include
  DOC "LibScrypt include directory")

FIND_LIBRARY (LIBSCRYPT_LIBRARY
  NAMES scrypt
  PATH_SUFFIXES lib
  DOC "LibScrypt release library")


MARK_AS_ADVANCED (LIBSCRYPT_INCLUDE_DIR LIBSCRYPT_LIBRARY)

IF(LIBSCRYPT_LIBRARY)
    MESSAGE(STATUS "LibScrypt - found")
ELSE(LIBSCRYPT_LIBRARY)
    MESSAGE(FATAL_ERROR "LibScrypt - not found")
ENDIF(LIBSCRYPT_LIBRARY)

ENDIF(NOT LIBSCRYPT_LIBRARY)
