include(FindPackageHandleStandardArgs)

if (GMP_INCLUDE_DIR AND GMP_LIBRARIES)
    set(GMP_FIND_QUIETLY TRUE)
else (GMP_INCLUDE_DIR AND GMP_LIBRARIES)
    set(GMP_FIND_QUIETLY FALSE)

    find_path(GMP_INCLUDE_DIR NAMES gmp.h )
    find_library(GMP_LIBRARIES NAMES gmp libgmp )
    find_library(GMPXX_LIBRARIES NAMES gmpxx libgmpxx )
endif (GMP_INCLUDE_DIR AND GMP_LIBRARIES)


FIND_PACKAGE_HANDLE_STANDARD_ARGS(GMP DEFAULT_MSG GMP_INCLUDE_DIR GMP_LIBRARIES)
mark_as_advanced(GMP_INCLUDE_DIR GMP_LIBRARIES)
