if (WIN32 OR MSVC)
    set(ver ${CMAKE_SYSTEM_VERSION})
    string(REPLACE "." "" ver ${ver})
    string(REGEX REPLACE "([0-9])" "0\\1" ver ${ver})
    add_definitions(-D_WIN32_WINNT=${ver})
    add_definitions(-D__WINDOWS_OS__)
elseif(APPLE)
    add_definitions(-D__APPLE_OS__)
elseif(UNIX)
    add_definitions(-D__LINUX_OS__)
endif()
