function(ADD_TEST_TARGET TARGET_NAME)
    ADD_TEST(build_${TARGET_NAME} "${CMAKE_COMMAND}" --build ${CMAKE_BINARY_DIR} --target ${TARGET_NAME})
    get_property(TARGET_PATH TARGET ${TARGET_NAME} PROPERTY LOCATION)
    ADD_TEST(run_${TARGET_NAME} ${TARGET_PATH})
    SET_TESTS_PROPERTIES (run_${TARGET_NAME} PROPERTIES DEPENDS build_${TARGET_NAME})
endfunction(ADD_TEST_TARGET)


enable_testing()
