function(ADD_TEST_TARGET TARGET_NAME)
    ADD_TEST(build_${TARGET_NAME} "${CMAKE_COMMAND}" --build ${CMAKE_BINARY_DIR} --target ${TARGET_NAME})
    ADD_TEST(NAME run_${TARGET_NAME} COMMAND ${TARGET_NAME})
    SET_TESTS_PROPERTIES (run_${TARGET_NAME} PROPERTIES DEPENDS build_${TARGET_NAME})
endfunction(ADD_TEST_TARGET)


enable_testing()
